import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createProject } from '../js/project.js';
const deps = path.join(os.tmpdir(), 'fundamentals-3d-qa/node_modules');
const threeURL = pathToFileURL(path.join(deps, 'three/build/three.module.js')).href;
const THREE = await import(threeURL);
const { JSDOM } = await import(pathToFileURL(path.join(deps, 'jsdom/lib/api.js')).href);
const source = (await fs.readFile(new URL('../js/lessons/accessoryExample.js', import.meta.url), 'utf8')).replace("from 'three'", `from '${threeURL}'`);
const { createAccessoryExample } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
test('reference module separates without changing learner project and restores its camera', async () => {
  const dom = new JSDOM('<div id="canvas-wrap"></div>');
  globalThis.document = dom.window.document;
  globalThis.matchMedia = () => ({ matches: true });
  globalThis.cancelAnimationFrame = () => {};
  const project = createProject();
  const before = project.serialize();
  const camera = new THREE.PerspectiveCamera(); camera.position.set(5, 4, 8);
  const scene = new THREE.Scene();
  const bot = new THREE.Group(); bot.position.x = -2; bot.rotation.y = Math.PI; scene.add(bot);
  const target = new THREE.Vector3(0, 1, 0);
  const creator = { project, viewport: { stage: { scene, camera, orbitCtrl: { target, update() {} } }, getObject: () => bot } };
  const example = createAccessoryExample(creator);
  example.show();
  const module = scene.getObjectByName('Back module example');
  assert.equal(module.children.length, 4);
  const positions = module.children.map(child => child.position.clone());
  assert.equal(await example.separate(), true);
  assert.equal(document.querySelector('button'), null, 'example has no separate floating controls');
  assert.ok(module.children.every((child, i) => child.position.distanceTo(positions[i]) > .1));
  example.hide();
  assert.equal(scene.getObjectByName('Back module example'), undefined);
  assert.deepEqual(camera.position.toArray(), [5, 4, 8]);
  assert.deepEqual(target.toArray(), [0, 1, 0]);
  assert.deepEqual(project.serialize(), before);
  assert.equal(project.history.canUndo, false);
  example.dispose(); dom.window.close();
});
