import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { connect } from './browser-session.mjs';
const b = await connect();
const output = new URL('../qa/', import.meta.url);
await fs.mkdir(output, { recursive: true });
const checks = [];
const check = (name, value) => { assert.ok(value, name); checks.push(name); };
const ev = b.evaluate;
const frame = () => ev('new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)))');
const capture = name => b.screenshot(new URL(`${name}.png`, output));
const active = () => ev('creator.project.get(creator.project.selection.activeId)');
const expand = async name => { if (await ev(`document.querySelector('[data-section="${name}"] .inspector-section-toggle').getAttribute('aria-expanded') !== 'true'`)) await b.click(`[data-section="${name}"] .inspector-section-toggle`); };
const key = async (key, code, modifiers = 0) => {
  await b.send('Input.dispatchKeyEvent', { type: 'keyDown', key, code, modifiers });
  await b.send('Input.dispatchKeyEvent', { type: 'keyUp', key, code, modifiers });
};
const fill = async (selector, text) => {
  await ev(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.focus();el.select()})()`);
  await b.send('Input.insertText', { text });
  await key('Tab', 'Tab');
};
try {
  await b.send('Log.clear'); b.errors.length = 0;
  await b.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false });
  await ev('delete window.creator');
  await b.send('Page.reload', { ignoreCache: true });
  await b.wait('!!window.creator && document.getElementById("loading").hidden', 25000);
  await ev('document.fonts.ready');
  check('Initial Gizmobot render and empty history', await ev('creator.viewport.getObject("gizmobot").children.length > 0 && !creator.project.history.canUndo'));
  await capture('default');
  await b.click('#add-toggle');
  check('Add menu opens', await ev('!document.getElementById("add-menu").hidden'));
  check('Add menu is anchored to the viewport Add control', await ev('document.getElementById("add-menu").parentElement.classList.contains("add-control") && document.getElementById("add-toggle").closest(".viewport-heading")'));
  check('Shape choices have distinct previews and concise labels', await ev(`(() => { const items=[...document.querySelectorAll('[data-shape]')]; return items.length===5 && new Set(items.map(item=>item.querySelector('.shape-icon').innerHTML)).size===5 && items.every(item=>item.querySelector('.shape-copy strong')?.textContent.trim()) && !document.querySelector('.shape-copy small'); })()`));
  check('Old Add card copy is removed', await ev('!document.body.textContent.includes("A little starting point for your next idea")'));
  await capture('add-menu');
  await key('Escape', 'Escape');
  check('Escape dismisses Add and restores focus', await ev('document.getElementById("add-menu").hidden && document.activeElement.id === "add-toggle"'));
  for (const shape of ['cube','sphere','cylinder','cone','plane']) {
    await b.click('#add-toggle'); await b.click(`[data-shape="${shape}"]`);
    check(`${shape} adds, selects, and renders`, await ev(`creator.project.get(creator.project.selection.activeId).type === '${shape}' && !!creator.viewport.getObject(creator.project.selection.activeId) && !!document.querySelector('.scene-row.is-selected')`));
  }
  const cube = await ev('creator.project.entities.find(e=>e.type==="cube").id');
  await b.click(`.scene-row[data-entity-id="${cube}"] .scene-name`);
  check('Outliner selection reaches Inspector', (await active()).id === cube && await ev('document.querySelector(".inspector-name-input").value === "Cube"'));
  await fill('.transform-group:nth-child(1) input', '1.5');
  check('Numeric position reaches model and mesh', await ev(`creator.project.get('${cube}').components.transform.position[0] === 1.5 && creator.viewport.getObject('${cube}').position.x === 1.5`));
  // Tab may focus the next numeric field; click Undo commits that no-op draft first.
  await b.click('#undo');
  check('Numeric transform is undoable', await ev(`creator.project.get('${cube}').components.transform.position[0] !== 1.5`));
  await b.click('#redo');
  await expand('geometry');
  await fill('.geometry-fields input', '1.8');
  check('Geometry rebuild reaches mesh', await ev(`creator.viewport.getObject('${cube}').geometry.parameters.width === 1.8`));
  await expand('appearance');
  await fill('.appearance-fields .numeric-input', '0.25');
  check('Roughness reaches material', await ev(`creator.viewport.getObject('${cube}').material.roughness === 0.25`));
  await ev(`(()=>{const el=document.querySelector('.color-input');el.focus();el.value='#3a8c9d';el.dispatchEvent(new Event('input',{bubbles:true}));el.blur()})()`);
  check('Color reaches material', await ev(`creator.viewport.getObject('${cube}').material.color.getHexString() === '3a8c9d'`));
  await b.click('#undo');
  check('Color undo restores prior material', await ev(`creator.viewport.getObject('${cube}').material.color.getHexString() !== '3a8c9d'`));
  await b.click('#redo');
  await fill('.inspector-name-input', 'My first shape');
  check('Rename syncs Outliner and object', await ev(`creator.viewport.getObject('${cube}').name === 'My first shape' && document.querySelector('[data-entity-id="${cube}"] .scene-name').textContent === 'My first shape'`));
  await b.click('[data-tool="move"]'); await frame();
  await capture('selected-primitive');
  // Select via an actual raycast in the viewport, using the rendered mesh centre.
  await b.click('[data-tool="select"]');
  await ev(`creator.project.updateTransform('${cube}',{position:[0,2.2,1.2]})`); await frame();
  const point = await ev(`(()=>{const o=creator.viewport.getObject('${cube}');const p=o.getWorldPosition(o.position.clone()).project(creator.viewport.stage.camera);const r=document.getElementById('cv').getBoundingClientRect();return {x:r.x+(p.x+1)*r.width/2,y:r.y+(1-p.y)*r.height/2}})()`);
  await ev('creator.project.selection.clear()');
  await b.mouse('mousePressed',point.x,point.y,{button:'left',clickCount:1}); await b.mouse('mouseReleased',point.x,point.y,{button:'left',clickCount:1});
  check('Viewport picking syncs Outliner and Inspector', (await active()).id === cube);
  await b.click('.object-actions button:first-child');
  check('Hide changes mesh visibility', await ev(`!creator.viewport.getObject('${cube}').visible`));
  await b.click('.object-actions button:first-child');
  check('Show can be repeated', await ev(`creator.viewport.getObject('${cube}').visible`));
  await b.click('.object-actions button:nth-child(3)');
  const duplicate = (await active()).id;
  check('Duplicate creates independent selected object', duplicate !== cube);
  await b.click('.object-actions button:nth-child(4)');
  check('Delete clears selected entity safely', await ev(`!creator.project.get('${duplicate}') && !creator.project.selection.activeId`));
  await b.click('#undo');
  check('Delete undo restores object and selection', (await active()).id === duplicate);
  await ev(`creator.project.selection.set(['${cube}','${duplicate}'])`);
  await expand('hierarchy');
  await b.click('.hierarchy-actions button:first-child');
  const group = (await active()).id;
  check('Group nests entities', await ev(`creator.project.children('${group}').length===2`));
  await b.click(`.scene-row[data-entity-id="${group}"] .scene-expander`);
  await capture('grouped-scene');
  // Hierarchy keeps its expanded state when selection changes.
  await b.click('.hierarchy-actions button:last-child');
  check('Ungroup preserves children', await ev(`!creator.project.get('${group}') && creator.project.get('${cube}').parentId === 'creation'`));
  await b.click('#undo');
  check('Ungroup undo restores nesting', await ev(`creator.project.children('${group}').length===2`));
  await b.click('#dock-toggle');
  check('Dock closes', await ev('document.getElementById("editor-dock").hidden'));
  await b.click('#dock-toggle');
  check('Dock reopens', await ev('!document.getElementById("editor-dock").hidden'));
  await b.click('#bottom-toggle');
  check('Bottom host opens', await ev('creator.bottomEditor.isOpen'));
  await b.click('#bottom-toggle');
  await ev('creator.setCapabilities({tools:{rotate:false,add:false},panels:{scene:false},inspectorSections:{geometry:false}})');
  check('Capabilities hide tools and contextual panels', await ev('document.querySelector("[data-tool=rotate]").hidden && document.getElementById("add-toggle").hidden && document.querySelector(".scene-panel").hidden && !document.querySelector("[data-section=geometry]")'));
  await ev('creator.setCapabilities({tools:{rotate:true,add:true},panels:{scene:true},inspectorSections:{geometry:true}})');
  await b.send('Emulation.setDeviceMetricsOverride', { width: 820, height: 850, deviceScaleFactor: 1, mobile: false }); await frame();
  check('Narrow resize closes dock and preserves viewport', await ev('creator.dock.getState()==="closed" && document.getElementById("canvas-wrap").clientWidth>700'));
  await b.click('#dock-toggle'); await frame();
  check('Narrow dock is modal overlay', await ev('document.getElementById("editor-dock").getAttribute("aria-modal")==="true" && getComputedStyle(document.getElementById("editor-dock")).position==="absolute"'));
  await capture('narrow-drawer');
  await key('Escape','Escape');
  check('Escape closes narrow drawer and returns focus', await ev('creator.dock.getState()==="closed" && document.activeElement.id==="dock-toggle"'));
  await b.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: false }); await frame();
  check('Phone layout avoids horizontal overflow', await ev('document.documentElement.scrollWidth===390 && document.getElementById("canvas-wrap").clientWidth>350'));
  await capture('phone');
  const errors = b.errors.filter(error => !error.url?.endsWith('/favicon.ico'));
  check('No runtime or module errors', errors.length === 0);
  await fs.writeFile(new URL('browser-results.json',output),JSON.stringify({checks,errors},null,2));
  console.log(JSON.stringify({passed:checks.length,checks},null,2));
} finally { b.close(); }
