import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const { JSDOM } = await import(pathToFileURL(path.join(os.tmpdir(), 'fundamentals-3d-qa/node_modules/jsdom/lib/api.js')));
const dom = new JSDOM('<aside id="dock"></aside>', { pretendToBeVisual: true });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, CustomEvent: dom.window.CustomEvent, CSS: { escape: s => s } });
const { createProject } = await import('../js/project.js');
const { createDock } = await import('../js/dock.js');
test('lesson capabilities hide untaught scene actions and transform fields, then restore them', () => {
 const project = createProject();
 const cube = project.addPrimitive('cube');
 const root = document.querySelector('#dock');
 const dock = createDock({ project, root });
 const config = { actions: { visibility: false, rename: false, duplicate: false, delete: false, group: false, ungroup: false, reparent: false }, transformFields: { position: false, rotation: false, scale: true }, inspectorSections: { geometry: false, appearance: false } };
 dock.setCapabilities(config);
 assert.equal(root.querySelectorAll('.transform-group').length, 1);
 assert.equal(root.querySelector('legend').textContent, 'Scale');
 assert.ok([...root.querySelectorAll('.scene-visibility')].every(el => el.hidden));
 assert.ok(root.querySelector('.inspector-name-input').readOnly);
 assert.ok(root.querySelector('.parent-select').closest('label').hidden);
 assert.ok([...root.querySelectorAll('.object-actions button')].filter(el => ['Duplicate','Delete'].includes(el.textContent)).every(el => el.hidden));
 project.selection.set('gizmobot'); project.selection.set(cube.id);
 assert.equal(root.querySelectorAll('.transform-group').length, 1);
 dock.setCapabilities({ actions: {}, transformFields: {}, inspectorSections: { geometry: true, appearance: true } });
 assert.equal(root.querySelectorAll('.transform-group').length, 3);
 assert.ok([...root.querySelectorAll('.scene-visibility')].every(el => !el.hidden));
 assert.equal(root.querySelector('.inspector-name-input').readOnly, false);
 dock.dispose();
});
