import * as THREE from 'three';
import { LIMITS } from './config.js';
import { state, getEntry, entryForObject3D, placeMount, distanceToPort, snapToPort, setMountActive } from './model.js';
import { portWorldPoint, setPortActive } from './gizmobot.js';
import { session, select, activeId } from './session.js';
import { pickables, restoreColor, highlight, targetCentre, gizmoTarget, setGizmoTarget } from './gizmos.js';
import { push } from './history.js';
import { clamp } from '../../../kit/js/utils.js';
let cv, camera, orbitCtrl, hovered = null, onChange = () => {}, snapArmed = false, modellingEnabled = true, canInteract = () => true;
const raycaster = new THREE.Raycaster(), ndc = new THREE.Vector2();
const drag = { kind: null, handle: null, target: null, pointerId: null, axis: null, startX: 0, startY: 0, ppu: 1, dir: { x: 1, y: 0 }, pos: new THREE.Vector3(), scale: new THREE.Vector3(), quat: new THREE.Quaternion(), centre: { x: 0, y: 0 }, distance: 1, angle: 0 };
export function initInteraction(stage, { onChange: cb, canInteract: allowed } = {}) { canInteract = allowed || (() => true); cv = document.getElementById('cv'); camera = stage.camera; orbitCtrl = stage.orbitCtrl; onChange = cb || onChange; cv.addEventListener('pointerdown', down, { capture: true }); window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); window.addEventListener('blur', cancel); cv.addEventListener('pointercancel', cancel); cv.addEventListener('pointermove', hover); }
export function setModellingEnabled(on) {
    modellingEnabled = on;
    if (!on) {
        restoreColor(hovered);
        hovered = null;
        select([]);
        setGizmoTarget(null);
        if (cv) cv.style.cursor = '';
    }
}
export const setMountPlacement = () => {};
export function setSnapArmed(on) { snapArmed = on; if (!on) { setPortActive(false); setMountActive(false); } }
export function showReadout(label, value, axis = null) { const el = document.getElementById('modal-readout'); if (!el) return; el.textContent = `${label}   ${value}`; el.className = axis ? `on axis-${axis}` : 'on'; }
export const hideReadout = () => document.getElementById('modal-readout')?.classList.remove('on');
const screen = p => { const v = p.clone().project(camera), r = cv.getBoundingClientRect(); return { x: r.left + (v.x + 1) * r.width / 2, y: r.top + (1 - v.y) * r.height / 2 }; };
const axisScreen = (centre, axis) => { const a = screen(centre), b = screen(centre.clone().add(axis)), x = b.x - a.x, y = b.y - a.y, length = Math.hypot(x, y) || 1; return { ppu: length, dir: { x: x / length, y: y / length } }; };
const ndcFor = e => { const r = cv.getBoundingClientRect(); ndc.set((e.clientX - r.left) / r.width * 2 - 1, -((e.clientY - r.top) / r.height * 2 - 1)); return ndc; };
function hitHandle(e) { raycaster.setFromCamera(ndcFor(e), camera); for (const item of pickables()) if (raycaster.intersectObject(item.mesh, false).length) return item.handle; return null; }
function hitObject(e) { raycaster.setFromCamera(ndcFor(e), camera); return raycaster.intersectObjects(state.entries.filter(x => x.kind !== 'group').map(x => x.mesh), false)[0]; }
function down(e) { if (!modellingEnabled || !canInteract() || e.button || session.modal) return; const handle = gizmoTarget() && hitHandle(e); if (handle) { e.stopPropagation(); begin(e, handle); return; } const hit = hitObject(e); if (!hit) { select([]); onChange('select'); return; } e.stopPropagation(); const entry = entryForObject3D(hit.object); const top = entry?.parentId && session.tool !== 'select' && !e.altKey ? getEntry(entry.parentId) : entry; if (top) { select(top.id); onChange('select'); if (session.tool === 'move') begin(e, { _kind: 'moveFree' }); } }
function begin(e, handle) { const target = gizmoTarget(); if (!target || (target !== state.root && !getEntry(activeId()))) return; orbitCtrl.enabled = false; session.dragging = true; drag.kind = handle._kind; drag.handle = handle; drag.target = target; drag.pointerId = e.pointerId; drag.startX = e.clientX; drag.startY = e.clientY; drag.pos.copy(target.position); drag.worldPos = target.getWorldPosition(new THREE.Vector3()); drag.moved = false; drag.scale.copy(target.scale); drag.quat.copy(target.quaternion); drag.axis = handle._axKey; drag.centre = screen(targetCentre()); if (drag.kind === 'moveFree') { drag.plane = new THREE.Plane().setFromNormalAndCoplanarPoint(camera.getWorldDirection(new THREE.Vector3()), target.getWorldPosition(new THREE.Vector3())); raycaster.setFromCamera(ndcFor(e), camera); drag.anchor = raycaster.ray.intersectPlane(drag.plane, new THREE.Vector3()); } else if (drag.kind === 'move' || drag.kind === 'scaleAxis') { const axis = new THREE.Vector3(drag.axis === 'x', drag.axis === 'y', drag.axis === 'z'); const info = axisScreen(targetCentre(), drag.kind === 'scaleAxis' ? axis.applyQuaternion(target.getWorldQuaternion(new THREE.Quaternion())) : axis); drag.ppu = info.ppu; drag.dir = info.dir; } else if (drag.kind === 'scaleUniform') drag.distance = Math.max(Math.hypot(e.clientX - drag.centre.x, e.clientY - drag.centre.y), 12); else drag.angle = Math.atan2(e.clientY - drag.centre.y, e.clientX - drag.centre.x); cv.setPointerCapture?.(e.pointerId); if (drag.kind !== 'moveFree') highlight(handle); }
function move(e) { if (!session.dragging || e.pointerId !== drag.pointerId) return; const target = drag.target, dx = e.clientX - drag.startX, dy = e.clientY - drag.startY, amount = (dx * drag.dir.x + dy * drag.dir.y) / drag.ppu; drag.moved ||= Math.hypot(dx, dy) > 2; if (drag.kind === 'moveFree') { raycaster.setFromCamera(ndcFor(e), camera); const point = raycaster.ray.intersectPlane(drag.plane, new THREE.Vector3()); if (point && drag.anchor) { const destination = drag.worldPos.clone().add(point.sub(drag.anchor)); target.position.copy(target.parent ? target.parent.worldToLocal(destination) : destination); } showReadout('MOVE', ''); } else if (drag.kind === 'move') { const destination = drag.worldPos.clone(); destination[drag.axis] += amount; target.position.copy(target.parent ? target.parent.worldToLocal(destination) : destination); showReadout('MOVE', drag.axis.toUpperCase()); } else if (drag.kind === 'scaleAxis') { target.scale.copy(drag.scale); target.scale[drag.axis] = clamp(drag.scale[drag.axis] + amount, LIMITS.scaleMin, LIMITS.scaleMax); showReadout('SCALE', drag.axis.toUpperCase()); } else if (drag.kind === 'scaleUniform') { const f = clamp(Math.hypot(e.clientX - drag.centre.x, e.clientY - drag.centre.y) / drag.distance, LIMITS.scaleMin / Math.min(drag.scale.x, drag.scale.y, drag.scale.z), LIMITS.scaleMax / Math.max(drag.scale.x, drag.scale.y, drag.scale.z)); target.scale.setScalar(1); target.scale.multiplyScalar(f); target.scale.multiply(drag.scale); showReadout('SCALE', 'all sides'); } else if (drag.kind === 'rotate') { const now = Math.atan2(e.clientY - drag.centre.y, e.clientX - drag.centre.x); target.quaternion.copy(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(drag.axis === 'x', drag.axis === 'y', drag.axis === 'z'), now - drag.angle).multiply(drag.quat)); showReadout('ROTATE', drag.axis.toUpperCase()); } placeMount(); if (snapArmed) { const near = distanceToPort(portWorldPoint()) <= LIMITS.snapDistance; setPortActive(near); setMountActive(near); } onChange(drag.kind.startsWith('move') ? 'move' : drag.kind === 'rotate' ? 'rotate' : 'scale'); }
function up(e) { if (!session.dragging || (e.pointerId !== undefined && e.pointerId !== drag.pointerId)) return; const snapped = snapArmed && drag.kind.startsWith('move') && drag.moved && snapToPort(portWorldPoint()); cv.releasePointerCapture?.(drag.pointerId); if (drag.kind !== 'moveFree') restoreColor(drag.handle); hovered = null; session.dragging = false; orbitCtrl.enabled = true; hideReadout(); if (snapped) { setPortActive(false); setMountActive(false); onChange('snapped'); } else { if (drag.moved) push(); onChange('commit'); } drag.kind = null; }
function cancel() { if (!session.dragging) return; drag.target.position.copy(drag.pos); drag.target.scale.copy(drag.scale); drag.target.quaternion.copy(drag.quat); placeMount(); setPortActive(false); setMountActive(false); cv.releasePointerCapture?.(drag.pointerId); if (drag.kind !== 'moveFree') restoreColor(drag.handle); hovered = null; session.dragging = false; orbitCtrl.enabled = true; hideReadout(); drag.kind = null; onChange('cancel'); }
function hover(e) { if (!modellingEnabled || !canInteract() || session.dragging || !gizmoTarget()) return; const h = hitHandle(e); if (h !== hovered) { restoreColor(hovered); hovered = h; } if (h) highlight(h); cv.style.cursor = h ? 'grab' : ''; }
export const isDragging = () => session.dragging;
